source("projeto_pratico/classes/db.R")
source("projeto_pratico/models/sales.R")
source("projeto_pratico/funcs/filters/sales.R")
source("projeto_pratico/funcs/formatters/sales.R")
source("projeto_pratico/main/vendas_metas.R")
source("projeto_pratico/main/distribuicao_valor_vendas.R")
source("projeto_pratico/main/correlacao_vendas_investimento.R")
library("glue")

engine <- hub$connect()
date_begin <- Sys.Date() - (30 * 3)
date_end <- Sys.Date()
query_sales <- glue_sql(query_sales, .con = engine)
data <- hub$exec_query(engine, query_sales)
data <- Format_sales(data)
data <- Filter_real_sales(data) 
data <- Filter_internet(data) 
Vendas_metas(data)
Distribuicao_Valor_Vendas(data)
Correlacao_vendas_investimento(data)